### ISSUE TITLE
Readme fix

### ISSUE THREAD

**Issue by zlatanvasovic** [karthikv/my-style#10]
So, project is interesting, but can you fix `README.md`?

Not big issue, just a visual improvment. ;)

Original:

``` markdown
control + m
```

Fix:

``` markdown
<kbd>Ctrl</kbd> + <kbd>M</kbd>
```

It looks like a <kbd>Ctrl</kbd> + <kbd>M</kbd>.

Also, you don't need to type notes into _()_.
Example:

> (Note: if you'd like this specific Techcrunch skin, it's available at styles/techcrunch.css.)

Fix:

> Note: if you'd like this specific Techcrunch skin, it's available at styles/techcrunch.css.

_P.S. I made issue because I don't open small pull requests. ;)_

**Comment by karthikv** [comment]
I'll update the keyboard shortcut, but parentheses are a stylistic issue. I prefer to have that line in parentheses because it doesn't flow with the other text; rather, it acts as more of a side-note.

**Comment by zlatanvasovic** [comment]
Ok. Just a formating... You can use core HTML5 elements in MD. :)
