### ISSUE TITLE
How does this differ from Stylish?

### ISSUE THREAD

**Issue by AlecRust** [karthikv/my-style#8]
How does this extension differ from the popular [Stylish](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en)? Any additional or better features?

**Comment by karthikv** [comment]
I think the primary differences are minimalism and target audience. With this extension, you press one keyboard shortcut, type your CSS in, and immediately see the visual changes, which are retained for future visits. Stylish's interface is more complex, and doesn't allow you to modify website designs as easily.

Additionally, Stylish seems to be tailored for generic (non-developer) use with the accompanying userstyles website. My Style, by contrast, is largely developer-centric, making it your job to write the CSS that defines how pages look. I do aim to add sharing in the future, but for now, My Style appears tailored to a developer/designer niche.

I don't think speaking about the differences really constitues a GitHub issue, though, as it doesn't address a feature request or a bug. I'd be glad to take this conversation offline, but for now, I'm closing the issue.

**Comment by AlecRust** [comment]
That's good information, thanks!
